Repository OSTA-group/osta, pull requests merged in 2024-05, with the labels that each got.

#4 Documentation 1 installation instructions
  .github/CONTRIBUTING.md
  package-lock.json
  package.json
  src/adapter/TypeAdapter.d.ts
  src/services/CompassService.d.ts
  src/types.d.ts
  tsconfig.docs.json
Labels: documentation

#9 Init trip and remove variables
  android/gradlew
  src/App.tsx
  src/components/ExtensionConfigurationVariableInput.tsx
  src/services/ExtensionService.ts
Labels: bug

#11 Update pull_request_template.md
  .github/pull_request_template.md
Labels: documentation

#12 Add * after required variables
  src/components/ExtensionConfigurationVariableInput.tsx
  src/pages/settings/ExtensionPropertiesScreen.tsx
Labels: enhancement

#15 Fix bug landmark id not being set to 0
  src/services/TripService.ts
Labels: bug

#24 Compass Issues and App Title
  .github/pull_request_template.md
  android/app/build.gradle
  android/app/src/main/java/io/osta/MainActivity.java
  android/app/src/main/res/values/strings.xml
  src/components/LandmarkCompassCard.tsx
  src/helpers/LocationHelper.d.ts
  src/helpers/LocationHelper.ts
  src/pages/LandmarkDetail.tsx
  tests/GeoFunctions.test.tsx
Labels: bug, documentation

#27 Added pull request workflow
  .github/workflows/pull-requests.yml
Labels: enhancement

#29 Closing save area modal when dismissed
  landmarks.json5
  src/pages/DownloadScreen.tsx
Labels: bug

#28 Fix bug: something went wrong while loading landmarks while database isn't initialised
  src/pages/MapScreen.tsx
Labels: bug

#32 Add tests to Services and Helpers
  src/api/ExtensionApi.d.ts
  src/api/ExtensionApi.ts
  src/api/MarketplaceApi.d.ts
  src/api/MarketplaceApi.ts
  src/hooks/useMarketplace.ts
  src/services/ExtensionService.ts
  tests/helpers/LandmarksHelper.test.ts
  tests/helpers/LocationHelper.test.ts
  tests/services/ExtensionService.test.ts
  tests/services/LandmarkService.test.ts
  tests/services/TripService.test.ts
Labels: documentation, enhancement

#33 Show distance when creating a trip
  .github/pull_request_template.md
  src/helpers/LandmarksHelper.ts
  src/helpers/LocationHelper.ts
  src/pages/trip/CreateTripScreen.tsx
  src/pages/trip/OrganiseTripScreen.tsx
  src/types.d.ts
  tests/helpers/LandmarksHelper.test.ts
Labels: enhancement

#36 Splash screen api
  android/app/capacitor.build.gradle
  android/app/src/main/res/drawable-land-hdpi/splash.png
  android/app/src/main/res/drawable-land-mdpi/splash.png
  android/app/src/main/res/drawable-land-xhdpi/splash.png
  android/app/src/main/res/drawable-land-xxhdpi/splash.png
  android/app/src/main/res/drawable-land-xxxhdpi/splash.png
  android/app/src/main/res/drawable-port-hdpi/splash.png
  android/app/src/main/res/drawable-port-mdpi/splash.png
  android/app/src/main/res/drawable-port-xhdpi/splash.png
  android/app/src/main/res/drawable-port-xxhdpi/splash.png
  android/app/src/main/res/drawable-port-xxxhdpi/splash.png
  android/app/src/main/res/drawable/splash.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/values/ic_launcher_background.xml
  android/app/src/main/res/values/styles.xml
  android/capacitor.settings.gradle
  capacitor.config.ts
  package-lock.json
  package.json
Labels: bug, enhancement

#38 Fix bug: scrollable loading page
  src/pages/MapScreen.tsx
Labels: bug

#41 Add slider to delete landmarks when planning a new trip
  src/pages/trip/CreateTripScreen.tsx
  src/pages/trip/OrganiseTripScreen.tsx
Labels: enhancement
