Repository OSTA-group/osta, pull requests merged in 2024-06, with the labels that each got.

#57 Update CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: documentation

#55 Update LICENSE
  LICENSE
Labels: documentation

#58 Map context provider and implementation
  src/App.tsx
  src/components/OfflineMapContainer.tsx
  src/contexts/MapContext.tsx
Labels: bug

#61 Fixed link to wikipedia extension
  README.md
Labels: documentation

#74 Update README.md
  README.md
Labels: documentation

#72 Geosearch input field for downloading areas
  package-lock.json
  package.json
  src/components/GeoSearchField.tsx
  src/components/css/DownloadScreen.css
  src/pages/DownloadScreen.tsx
Labels: enhancement

#70 Show trip details after trip
  src/components/LandmarkMarker.tsx
  src/components/OfflineMapContainer.tsx
  src/components/css/LeafletMap.css
  src/pages/DownloadScreen.tsx
  src/pages/MapScreen.tsx
Labels: enhancement

#77 Resize bounding box when downloading bases on size of selection rectangle
  src/pages/DownloadScreen.tsx
Labels: bug

#79 Dark mode styling fix for geosearch and zoom control
  src/components/GeoSearchField.tsx
  src/components/css/GeoSearchField.css
  src/components/css/LeafletMap.css
Labels: bug

#86 Popup to confirm cancelling a trip
  src/components/css/LeafletMap.css
  src/components/css/MapScreen.css
  src/pages/MapScreen.tsx
Labels: enhancement

#88 Override ion-color variables and vulnerability fix
  package-lock.json
  src/components/LandmarkMarker.tsx
  src/components/css/LeafletMap.css
  src/pages/DownloadScreen.tsx
  src/pages/MapScreen.tsx
  src/pages/MarketplaceScreen.tsx
  src/pages/settings/AreasSettingsScreen.tsx
  src/pages/settings/ExtensionsSettingsScreen.tsx
  src/pages/trip/CreateTripScreen.tsx
  src/pages/trip/OrganiseTripScreen.tsx
  src/theme/variables.css
Labels: enhancement
